AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Allows VGS to replicate from customer account via S3 replication.

  The file is run in the VGS account.

Parameters:

  CustomerVgsVaultId:
    Type: String
    Description: Customer's VGS Vault Id

  CustomerAwsAccountId:
    Type: String
    Description: Source bucket owner AWS account ID.

  Version:
    Type: String
    Description: Discriminator in case multiple instances are provisioned
    Default: '01'

Resources:

  InternalSourceS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'vgs-files-from-customer-for-${CustomerVgsVaultId}-${Version}'
      VersioningConfiguration:
        Status: Enabled
      Tags:
      # https://verygoodsecurity.atlassian.net/wiki/spaces/INFRA/pages/1359610177/Tagging+Labeling+Guidelines+Practical+Guide
      - Key: vgs:tenant
        Value: !Ref CustomerVgsVaultId
      - Key: vgs:product
        Value: mft

  BucketReplicationPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Sub 'vgs-files-from-customer-for-${CustomerVgsVaultId}-${Version}'
      PolicyDocument:
        Statement:
        - Sid: Replication policy
          Effect: Allow
          Principal:
            AWS: !Join ['',['arn:aws:iam::', !Ref CustomerAwsAccountId, ':root']]
          Action:
            - 's3:ReplicateObject'
            - 's3:ReplicateDelete'
            - 's3:ReplicateTags'
            - 's3:GetObjectVersionTagging'
            - 's3:GetBucketVersioning'
            - 's3:PutBucketVersioning'
            - 's3:ObjectOwnerOverrideToBucketOwner'
          Resource: ## destination bucket
            - !Sub 'arn:aws:s3:::vgs-files-from-customer-for-${CustomerVgsVaultId}-${Version}'
            - !Sub 'arn:aws:s3:::vgs-files-from-customer-for-${CustomerVgsVaultId}-${Version}/*'

Outputs:
  CustomerVgsVaultId:
    Value: !Ref CustomerVgsVaultId
  CustomerAwsAccountId:
    Value: !Ref CustomerAwsAccountId
  VgsS3Bucket:
    Value: !Ref InternalSourceS3Bucket
    Description: VGS S3 bucket that will receive replicated files
